services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-odoo}
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
    volumes:
      - ./odoo_data/postgres:/var/lib/postgresql/data

  odoo:
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      PORT: 8069
      ODOO_ADMIN_PASSWORD: ${ODOO_ADMIN_PASSWORD:-admin}
      ODOO_DATABASE_HOST: db
      ODOO_DATABASE_PORT: 5432
      ODOO_DATABASE_USER: ${POSTGRES_USER:-odoo}
      ODOO_DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-odoo}
      ODOO_DATABASE_NAME: ${POSTGRES_DB:-odoo}
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - ./odoo_data/filestore:/var/lib/odoo
