[options]
admin_passwd = ${ODOO_ADMIN_PASSWORD}
db_host = ${ODOO_DATABASE_HOST}
db_port = ${ODOO_DATABASE_PORT}
db_user = ${ODOO_DATABASE_USER}
db_password = ${ODOO_DATABASE_PASSWORD}
db_name = ${ODOO_DATABASE_NAME}
proxy_mode = True
without_demo = True
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
data_dir = /var/lib/odoo
http_port = ${PORT}
log_level = info
